version: "3"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Madrid
    volumes:
      - ./config:/config
      #- ruta/a/carpeta/media:/media
      #- ruta/a/otra/carpeta/extra:/descargas
      - ${MEDIA}:/media
      - ${STORAGE}:/descargas
    ports:
      - 8096:8096
    restart: unless-stopped
volumes:
  jellyfin-config:
